#!/bin/bash

# Easy setup for testing

cp -R .config/* ~/.config/
chmod -R +x ~/.config/bspwm/scripts
sudo pacman -Syu --needed --noconfirm - < packages-repository.txt
dbus-launch dconf load / < xed.dconf
