#! /bin/sh

# Default
bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2

bspc config window_gap          10

bspc config split_ratio          0.50

bspc config single_monocle true

bspc config borderless_monocle true

bspc config gapless_monocle true

bspc config pointer_follows_focus true

bspc config center_pseudo_tiled true

# Application Rules
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Screenkey manage=off
bspc rule -a lxappearance state=floating center=true
bspc rule -a lxterminal state=floating center=true sticky=true
bspc rule -a file-roller state=floating center=true
bspc rule -a floaterm state=floating center=true
bspc rule -a yad state=floating

# Borders
bspc config normal_border_color
bspc config active_border_color  \#145f9d
bspc config focused_border_color \#145f9d

# Source Autostart File
$HOME/.config/bspwm/autostart
